name: Update README

on:
  push:
    branches:
      - main

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get last 5 projects
        id: get_projects
        run: |
          echo "## My Top 5 Projects" >> README.md
          echo "Here are my latest projects:" >> README.md
          for dir in $(ls -d */ | sort -r | head -n 5); do
            project_name=$(basename "$dir")
            echo "- [$project_name](https://github.com/RustamovAkrom/$project_name)" >> README.md
          done

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add README.md
          git commit -m "Update README with latest projects" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: git push https://$GITHUB_TOKEN@github.com/RustamovAkrom/RustamovAkrom.git main
